import React, { createContext, useContext, useState } from "react";

const languages = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
];

const LanguageContext = createContext(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem("selectedLanguage") || "en";
  });

  const setLanguage = (language) => {
    setCurrentLanguage(language);
    localStorage.setItem("selectedLanguage", language);
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languages };

const translations = {
  en: {
    "nav.home": "Home",
    "nav.crowdMonitor": "Crowd Monitor",
    "nav.darshanQueue": "Darshan Queue",
    "nav.templeMap": "Temple Map",
    "nav.emergency": "Emergency",
    "nav.services": "Services",
    "nav.analytics": "Analytics",
    "nav.language": "Language",
    "hero.title": "Somnath Temple",
    "hero.subtitle": "Divine Crowd Management System",
    "hero.description":
      "Experience seamless darshan with real-time crowd monitoring, virtual queues, and smart navigation at the sacred Somnath Jyotirlinga.",
    "hero.getStarted": "Get Started",
    "hero.viewMap": "View Temple Map",
    "crowd.title": "Real-time Crowd Monitoring",
    "crowd.currentFootfall": "Current Footfall",
    "crowd.capacity": "Temple Capacity",
    "crowd.waitingTime": "Average Waiting Time",
    "crowd.crowdDensity": "Crowd Density",
    "crowd.low": "Low",
    "crowd.moderate": "Moderate",
    "crowd.high": "High",
    "crowd.critical": "Critical",
    "queue.title": "Darshan Queue Management",
    "queue.bookSlot": "Book Darshan Slot",
    "queue.currentToken": "Current Token",
    "queue.yourToken": "Your Token",
    "queue.estimatedWait": "Estimated Wait Time",
    "queue.selectTime": "Select Preferred Time",
    "queue.book": "Book Slot",
    "map.title": "Temple Map & Navigation",
    "map.legend": "Legend",
    "map.sanctum": "Sanctum Sanctorum",
    "map.mandapa": "Mandapa",
    "map.pradakshina": "Pradakshina Path",
    "map.entrance": "Main Entrance",
    "map.exit": "Exit Gate",
    "map.facilities": "Facilities",
    "map.parking": "Parking",
    "map.lightShow": "Light & Sound Show",
    "emergency.title": "Emergency Services",
    "emergency.medicalHelp": "Medical Emergency",
    "emergency.security": "Security Alert",
    "emergency.lostFound": "Lost & Found",
    "emergency.callNow": "Call Now",
    "services.title": "Temple Services & Information",
    "services.timings": "Temple Timings",
    "services.aarti": "Aarti Timings",
    "services.attractions": "Nearby Attractions",
    "services.accommodation": "Accommodation",
    "services.transportation": "How to Reach",
    "analytics.title": "Crowd Analytics Dashboard",
    "analytics.hourlyFlow": "Hourly Visitor Flow",
    "analytics.peakHours": "Peak Hours Analysis",
    "analytics.predictions": "Crowd Predictions",
    "common.minutes": "minutes",
    "common.hours": "hours",
    "common.people": "people",
    "common.capacity": "capacity",
  },

  hi: {
    "nav.home": "होम",
    "nav.crowdMonitor": "भीड़ निगरानी",
    "nav.darshanQueue": "दर्शन क्यू",
    "nav.templeMap": "मंदिर मानचित्र",
    "nav.emergency": "आपातकाल",
    "nav.services": "सेवाएं",
    "nav.analytics": "विश्लेषण",
    "nav.language": "भाषा",
    "hero.title": "सोमनाथ मंदिर",
    "hero.subtitle": "दिव्य भीड़ प्रबंधन प्रणाली",
    "hero.description":
      "पवित्र सोमनाथ ज्योतिर्लिंग में रियल-टाइम भीड़ निगरानी, वर्चुअल क्यू और स्मार्ट नेवीगेशन के साथ निर्बाध दर्शन का अनुभव करें।",
    "hero.getStarted": "शुरू करें",
    "hero.viewMap": "मंदिर मानचित्र देखें",
    "crowd.title": "रियल-टाइम भीड़ निगरानी",
    "crowd.currentFootfall": "वर्तमान आगंतुक संख्या",
    "crowd.capacity": "मंदिर क्षमता",
    "crowd.waitingTime": "औसत प्रतीक्षा समय",
    "crowd.crowdDensity": "भीड़ घनत्व",
    "crowd.low": "कम",
    "crowd.moderate": "मध्यम",
    "crowd.high": "अधिक",
    "crowd.critical": "गंभीर",
    "queue.title": "दर्शन क्यू प्रबंधन",
    "queue.bookSlot": "दर्शन स्लॉट बुक करें",
    "queue.currentToken": "वर्तमान टोकन",
    "queue.yourToken": "आपका टोकन",
    "queue.estimatedWait": "अनुमानित प्रतीक्षा समय",
    "queue.selectTime": "पसंदीदा समय चुनें",
    "queue.book": "स्लॉट बुक करें",
    "map.title": "मंदिर मानचित्र और नेवीगेशन",
    "map.legend": "विवरण",
    "map.sanctum": "गर्भगृह",
    "map.mandapa": "मंडप",
    "map.pradakshina": "प्रदक्षिणा पथ",
    "map.entrance": "मुख्य प्रवेश",
    "map.exit": "निकास द्वार",
    "map.facilities": "सुविधाएं",
    "map.parking": "पार्किंग",
    "map.lightShow": "लाइट एंड साउंड शो",
    "emergency.title": "आपातकालीन सेवाएं",
    "emergency.medicalHelp": "चिकित्सा आपातकाल",
    "emergency.security": "सुरक्षा अलर्ट",
    "emergency.lostFound": "खोया पाया",
    "emergency.callNow": "अभी कॉल करें",
    "services.title": "मंदिर सेवाएं और जानकारी",
    "services.timings": "मंदिर का समय",
    "services.aarti": "आरती का समय",
    "services.attractions": "निकटवर्ती आकर्षण",
    "services.accommodation": "आवास",
    "services.transportation": "कैसे पहुंचें",
    "analytics.title": "भीड़ विश्लेषण डैशबोर्ड",
    "analytics.hourlyFlow": "प्रति घंटा आगंतुक प्रवाह",
    "analytics.peakHours": "पीक ऑवर्स विश्लेषण",
    "analytics.predictions": "भीड़ की भविष्यवाणी",
    "common.minutes": "मिनट",
    "common.hours": "घंटे",
    "common.people": "लोग",
    "common.capacity": "क्षमता",
  },

  gu: {
    "nav.home": "હોમ",
    "nav.crowdMonitor": "ભીડ નિરીક્ષણ",
    "nav.darshanQueue": "દર્શન કતાર",
    "nav.templeMap": "મંદિર નકશો",
    "nav.emergency": "કટોકટી",
    "nav.services": "સેવાઓ",
    "nav.analytics": "વિશ્લેષણ",
    "nav.language": "ભાષા",
    "hero.title": "સોમનાથ મંદિર",
    "hero.subtitle": "દિવ્ય ભીડ વ્યવસ્થાપન સિસ્ટમ",
    "hero.description":
      "પવિત્ર સોમનાથ જ્યોતિર્લિંગમાં રિયલ-ટાઇમ ભીડ નિરીક્ષણ, વર્ચ્યુઅલ કતાર અને સ્માર્ટ નેવિગેશન સાથે નિર્બાધ દર્શનનો અનુભવ કરો.",
    "hero.getStarted": "શરૂ કરો",
    "hero.viewMap": "મંદિર નકશો જુઓ",
    "crowd.title": "રિયલ-ટાઇમ ભીડ નિરીક્ષણ",
    "crowd.currentFootfall": "વર્તમાન આગંતુક સંખ્યા",
    "crowd.capacity": "મંદિર ક્ષમતા",
    "crowd.waitingTime": "સરેરાશ રાહ જોવાનો સમય",
    "crowd.crowdDensity": "ભીડની ઘનતા",
    "crowd.low": "ઓછી",
    "crowd.moderate": "મધ્યમ",
    "crowd.high": "વધારે",
    "crowd.critical": "ગંભીર",
    "queue.title": "દર્શન કતાર વ્યવસ્થાપન",
    "queue.bookSlot": "દર્શન સ્લોટ બુક કરો",
    "queue.currentToken": "વર્તમાન ટોકન",
    "queue.yourToken": "તમારું ટોકન",
    "queue.estimatedWait": "અનુમાનિત રાહ જોવાનો સમય",
    "queue.selectTime": "પસંદગીનો સમય પસંદ કરો",
    "queue.book": "સ્લોટ બુક કરો",
    "map.title": "મંદિર નકશો અને નેવિગેશન",
    "map.legend": "વિગત",
    "map.sanctum": "ગર્ભગૃહ",
    "map.mandapa": "મંડપ",
    "map.pradakshina": "પ્રદક્ષિણા માર્ગ",
    "map.entrance": "મુખ્ય પ્રવેશ",
    "map.exit": "બહાર નીકળવાનો દરવાજો",
    "map.facilities": "સુવિધાઓ",
    "map.parking": "પાર્કિંગ",
    "map.lightShow": "લાઇટ એન્ડ સાઉન્ડ શો",
    "emergency.title": "કટોકટીની સેવાઓ",
    "emergency.medicalHelp": "તબીબી કટોકટી",
    "emergency.security": "સુરક્ષા ચેતવણી",
    "emergency.lostFound": "ખોવાયેલું મળ્યું",
    "emergency.callNow": "હવે કૉલ કરો",
    "services.title": "મંદિર સેવાઓ અને માહિતી",
    "services.timings": "મંદિરનો સમય",
    "services.aarti": "આરતીનો સમય",
    "services.attractions": "નજીકના આકર્ષણો",
    "services.accommodation": "રહેઠાણ",
    "services.transportation": "કેવી રીતે પહોંચવું",
    "analytics.title": "ભીડ વિશ્લેષણ ડેશબોર્ડ",
    "analytics.hourlyFlow": "કલાકદીઠ આગંતુક પ્રવાહ",
    "analytics.peakHours": "પીક અવર્સ વિશ્લેષણ",
    "analytics.predictions": "ભીડની આગાહી",
    "common.minutes": "મિનિટ",
    "common.hours": "કલાક",
    "common.people": "લોકો",
    "common.capacity": "ક્ષમતા",
  },

  mr: {
    "nav.home": "होम",
    "nav.crowdMonitor": "गर्दी निरीक्षण",
    "nav.darshanQueue": "दर्शन रांग",
    "nav.templeMap": "मंदिर नकाशा",
    "nav.emergency": "आणीबाणी",
    "nav.services": "सेवा",
    "nav.analytics": "विश्लेषण",
    "nav.language": "भाषा",
    "hero.title": "सोमनाथ मंदिर",
    "hero.subtitle": "दिव्य गर्दी व्यवस्थापन प्रणाली",
    "hero.description":
      "पवित्र सोमनाथ ज्योतिर्लिंगमध्ये रिअल-टाइम गर्दी निरीक्षण, व्हर्च्युअल रांग आणि स्मार्ट नेव्हिगेशनसह निर्बाध दर्शनचा अनुभव घ्या.",
    "hero.getStarted": "सुरुवात करा",
    "hero.viewMap": "मंदिर नकाशा पहा",
    "crowd.title": "रिअल-टाइम गर्दी निरीक्षण",
    "crowd.currentFootfall": "सध्याची पायदळी",
    "crowd.capacity": "मंदिर क्षमता",
    "crowd.waitingTime": "सरासरी प्रतीक्षा वेळ",
    "crowd.crowdDensity": "गर्दीची घनता",
    "crowd.low": "कमी",
    "crowd.moderate": "मध्यम",
    "crowd.high": "जास्त",
    "crowd.critical": "गंभीर",
    "queue.title": "दर्शन रांग व्यवस्थापन",
    "queue.bookSlot": "दर्शन स्लॉट बुक करा",
    "queue.currentToken": "सध्याचा टोकन",
    "queue.yourToken": "तुमचा टोकन",
    "queue.estimatedWait": "अंदाजित प्रतीक्षा वेळ",
    "queue.selectTime": "पसंतीची वेळ निवडा",
    "queue.book": "स्लॉट बुक करा",
    "common.minutes": "मिनिटे",
    "common.hours": "तास",
    "common.people": "लोक",
    "common.capacity": "क्षमता",
  },

  ta: {
    "nav.home": "வீடு",
    "nav.language": "மொழி",
    "hero.title": "சோமநாத் கோயில்",
    "hero.getStarted": "தொடங்குங்கள்",
    "common.minutes": "நிமிடங்கள்",
    "common.hours": "மணி நேரம்",
    "common.people": "மக்கள்",
    "common.capacity": "திறன்",
  },

  te: {
    "nav.home": "హోమ్",
    "nav.language": "భాష",
    "hero.title": "సోమనాథ్ దేవాలయం",
    "hero.getStarted": "ప్రారంభించండి",
    "common.minutes": "నిమిషాలు",
    "common.hours": "గంటలు",
    "common.people": "ప్రజలు",
    "common.capacity": "సామర్థ్యం",
  },

  bn: {
    "nav.home": "হোম",
    "nav.language": "ভাষা",
    "hero.title": "সোমনাথ মন্দির",
    "hero.getStarted": "শুরু করুন",
    "common.minutes": "মিনিট",
    "common.hours": "ঘন্টা",
    "common.people": "মানুষ",
    "common.capacity": "ক্ষমতা",
  },
};
