import React, { createContext, useContext, useState } from "react";

const languages = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "sa", name: "Sanskrit", nativeName: "संस्कृतम्" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
];

const LanguageContext = createContext(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem("selectedLanguage") || "en";
  });

  const setLanguage = (language) => {
    setCurrentLanguage(language);
    localStorage.setItem("selectedLanguage", language);
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languages };

const translations = {
  en: {
    "nav.home": "Home",
    "nav.crowdMonitor": "Crowd Monitor",
    "nav.darshanQueue": "Darshan Queue",
    "nav.templeMap": "Temple Map",
    "nav.emergency": "Emergency",
    "nav.services": "Services",
    "nav.analytics": "Analytics",
    "nav.language": "Language",
    "hero.title": "Somnath Temple",
    "hero.subtitle": "Divine Crowd Management System",
    "hero.description":
      "Experience seamless darshan with real-time crowd monitoring, virtual queues, and smart navigation at the sacred Somnath Jyotirlinga.",
    "hero.getStarted": "Get Started",
    "hero.viewMap": "View Temple Map",
    "crowd.title": "Real-time Crowd Monitoring",
    "crowd.currentFootfall": "Current Footfall",
    "crowd.capacity": "Temple Capacity",
    "crowd.waitingTime": "Average Waiting Time",
    "crowd.crowdDensity": "Crowd Density",
    "crowd.low": "Low",
    "crowd.moderate": "Moderate",
    "crowd.high": "High",
    "crowd.critical": "Critical",
    "queue.title": "Darshan Queue Management",
    "queue.bookSlot": "Book Darshan Slot",
    "queue.currentToken": "Current Token",
    "queue.yourToken": "Your Token",
    "queue.estimatedWait": "Estimated Wait Time",
    "queue.selectTime": "Select Preferred Time",
    "queue.book": "Book Slot",
    "map.title": "Temple Map & Navigation",
    "map.legend": "Legend",
    "map.sanctum": "Sanctum Sanctorum",
    "map.mandapa": "Mandapa",
    "map.pradakshina": "Pradakshina Path",
    "map.entrance": "Main Entrance",
    "map.exit": "Exit Gate",
    "map.facilities": "Facilities",
    "map.parking": "Parking",
    "map.lightShow": "Light & Sound Show",
    "emergency.title": "Emergency Services",
    "emergency.medicalHelp": "Medical Emergency",
    "emergency.security": "Security Alert",
    "emergency.lostFound": "Lost & Found",
    "emergency.callNow": "Call Now",
    "services.title": "Temple Services & Information",
    "services.timings": "Temple Timings",
    "services.aarti": "Aarti Timings",
    "services.attractions": "Nearby Attractions",
    "services.accommodation": "Accommodation",
    "services.transportation": "How to Reach",
    "analytics.title": "Crowd Analytics Dashboard",
    "analytics.hourlyFlow": "Hourly Visitor Flow",
    "analytics.peakHours": "Peak Hours Analysis",
    "analytics.predictions": "Crowd Predictions",
    "common.minutes": "minutes",
    "common.hours": "hours",
    "common.people": "people",
    "common.capacity": "capacity",
  },

  hi: {
    "nav.home": "होम",
    "nav.crowdMonitor": "भीड़ निगरानी",
    "nav.darshanQueue": "दर्शन क्यू",
    "nav.templeMap": "मंदिर मानचित्र",
    "nav.emergency": "आपातकाल",
    "nav.services": "सेवाएं",
    "nav.analytics": "विश्लेषण",
    "nav.language": "भाषा",
    "hero.title": "सोमनाथ मंदिर",
    "hero.subtitle": "दिव्य भीड़ प्रबंधन प्रणाली",
    "hero.description":
      "पवित्र सोमनाथ ज्योतिर्लिंग में रियल-टाइम भीड़ निगरानी, वर्चुअल क्यू और स्मार्ट नेवीगेशन के साथ निर्बाध दर्शन का अनुभव करें।",
    "hero.getStarted": "शुरू करें",
    "hero.viewMap": "मंदिर मानचित्र देखें",
    "crowd.title": "रियल-टाइम भीड़ निगरानी",
    "crowd.currentFootfall": "वर्तमान आगंतुक संख्या",
    "crowd.capacity": "मंदिर क्षमता",
    "crowd.waitingTime": "औसत प्रतीक्षा समय",
    "crowd.crowdDensity": "भीड़ घनत्व",
    "crowd.low": "कम",
    "crowd.moderate": "मध्यम",
    "crowd.high": "अधिक",
    "crowd.critical": "गंभीर",
    "queue.title": "दर्शन क्यू प्रबंधन",
    "queue.bookSlot": "दर्शन स्लॉट बुक करें",
    "queue.currentToken": "वर्तमान टोकन",
    "queue.yourToken": "आपका टोकन",
    "queue.estimatedWait": "अनुमानित प्रतीक्षा समय",
    "queue.selectTime": "पसंदीदा समय चुनें",
    "queue.book": "स्लॉट बुक करें",
    "map.title": "मंदिर मानचित्र और नेवीगेशन",
    "map.legend": "विवरण",
    "map.sanctum": "गर्भगृह",
    "map.mandapa": "मंडप",
    "map.pradakshina": "प्रदक्षिणा पथ",
    "map.entrance": "मुख्य प्रवेश",
    "map.exit": "निकास द्वार",
    "map.facilities": "सुविधाएं",
    "map.parking": "पार्किंग",
    "map.lightShow": "लाइट एंड साउंड शो",
    "emergency.title": "आपातकालीन सेवाएं",
    "emergency.medicalHelp": "चिकित्सा आपातकाल",
    "emergency.security": "सुरक्षा अलर्ट",
    "emergency.lostFound": "खोया पाया",
    "emergency.callNow": "अभी कॉल करें",
    "services.title": "मंदिर सेवाएं और जानकारी",
    "services.timings": "मंदिर का समय",
    "services.aarti": "आरती का समय",
    "services.attractions": "निकटवर्ती आकर्षण",
    "services.accommodation": "आवास",
    "services.transportation": "कैसे पहुंचें",
    "analytics.title": "भीड़ विश्लेषण डैशबोर्ड",
    "analytics.hourlyFlow": "प्रति घंटा आगंतुक प्रवाह",
    "analytics.peakHours": "पीक ऑवर्स विश्लेषण",
    "analytics.predictions": "भीड़ की भविष्यवाणी",
    "common.minutes": "मिनट",
    "common.hours": "घंटे",
    "common.people": "लोग",
    "common.capacity": "क्षमता",
  },

  gu: {
    "nav.home": "હોમ",
    "nav.crowdMonitor": "ભીડ નિરીક્ષણ",
    "nav.darshanQueue": "દર્શન કતાર",
    "nav.templeMap": "મંદિર નકશો",
    "nav.emergency": "કટોકટી",
    "nav.services": "સેવાઓ",
    "nav.analytics": "વિશ્લેષણ",
    "nav.language": "ભાષા",
    "hero.title": "સોમનાથ મંદિર",
    "hero.subtitle": "દિવ્ય ભીડ વ્યવસ્થાપન સિસ્ટમ",
    "hero.description":
      "પવિત્ર સોમનાથ જ્યોતિર્લિંગમાં રિયલ-ટાઇમ ભીડ નિરીક્ષણ, વર્ચ્યુઅલ કતાર અને સ્માર્ટ નેવિગેશન સાથે નિર્બાધ દર્શનનો અનુભવ કરો.",
    "hero.getStarted": "શરૂ કરો",
    "hero.viewMap": "મંદિર નકશો જુઓ",
    "crowd.title": "રિયલ-ટાઇમ ભીડ નિરીક્ષણ",
    "crowd.currentFootfall": "વર્તમાન આગંતુક સંખ્યા",
    "crowd.capacity": "મંદિર ક્ષમતા",
    "crowd.waitingTime": "સરેરાશ રાહ જોવાનો સમય",
    "crowd.crowdDensity": "ભીડની ઘનતા",
    "crowd.low": "ઓછી",
    "crowd.moderate": "મધ્યમ",
    "crowd.high": "વધારે",
    "crowd.critical": "ગંભીર",
    "queue.title": "દર્શન કતાર વ્યવસ્થાપન",
    "queue.bookSlot": "દર્શન સ્લોટ બુક કરો",
    "queue.currentToken": "વર્તમાન ટોકન",
    "queue.yourToken": "તમારું ટોકન",
    "queue.estimatedWait": "અનુમાનિત રાહ જોવાનો સમય",
    "queue.selectTime": "પસંદગીનો સમય પસંદ કરો",
    "queue.book": "સ્લોટ બુક કરો",
    "map.title": "મંદિર નકશો અને નેવિગેશન",
    "map.legend": "વિગત",
    "map.sanctum": "ગર્ભગૃહ",
    "map.mandapa": "મંડપ",
    "map.pradakshina": "પ્રદક્ષિણા માર્ગ",
    "map.entrance": "મુખ્ય પ્રવેશ",
    "map.exit": "બહાર નીકળવાનો દરવાજો",
    "map.facilities": "સુવિધાઓ",
    "map.parking": "પાર્કિંગ",
    "map.lightShow": "લાઇટ એન્ડ સાઉન્ડ શો",
    "emergency.title": "કટોકટીની સેવાઓ",
    "emergency.medicalHelp": "તબીબી કટોકટી",
    "emergency.security": "સુરક્ષા ચેતવણી",
    "emergency.lostFound": "ખોવાયેલું મળ્યું",
    "emergency.callNow": "હવે કૉલ કરો",
    "services.title": "મંદિર સેવાઓ અને માહિતી",
    "services.timings": "મંદિરનો સમય",
    "services.aarti": "આરતીનો સમય",
    "services.attractions": "નજીકના આકર્ષણો",
    "services.accommodation": "રહેઠાણ",
    "services.transportation": "કેવી રીતે પહોંચવું",
    "analytics.title": "ભીડ વિશ્લેષણ ડેશબોર્ડ",
    "analytics.hourlyFlow": "કલાકદીઠ આગંતુક પ્રવાહ",
    "analytics.peakHours": "પીક અવર્સ વિશ્લેષણ",
    "analytics.predictions": "ભીડની આગાહી",
    "common.minutes": "મિનિટ",
    "common.hours": "કલાક",
    "common.people": "લોકો",
    "common.capacity": "ક્ષમતા",
  },

  mr: {
    "nav.home": "होम",
    "nav.crowdMonitor": "गर्दी निरीक्षण",
    "nav.darshanQueue": "दर्शन रांग",
    "nav.templeMap": "मंदिर नकाशा",
    "nav.emergency": "आणीबाणी",
    "nav.services": "सेवा",
    "nav.analytics": "विश्लेषण",
    "nav.language": "भाषा",
    "hero.title": "सोमनाथ मंदिर",
    "hero.subtitle": "दिव्य गर्दी व्यवस्थापन प्रणाली",
    "hero.description":
      "पवित्र सोमनाथ ज्योतिर्लिंगमध्ये रिअल-टाइम गर्दी निरीक्षण, व्हर्च्युअल रांग आणि स्मार्ट नेव्हिगेशनसह निर्बाध दर्शनचा अनुभव घ्या.",
    "hero.getStarted": "सुरुवात करा",
    "hero.viewMap": "मंदिर नकाशा पहा",
    "crowd.title": "रिअल-टाइम गर्दी निरीक्षण",
    "crowd.currentFootfall": "सध्याची भाविक संख्या",
    "crowd.capacity": "मंदिर क्षमता",
    "crowd.waitingTime": "सरासरी प्रतीक्षा वेळ",
    "crowd.crowdDensity": "गर्दीची घनता",
    "crowd.low": "कमी",
    "crowd.moderate": "मध्यम",
    "crowd.high": "जास्त",
    "crowd.critical": "गंभीर",
    "queue.title": "दर्शन रांग व्यवस्थापन",
    "queue.bookSlot": "दर्शन स्लॉट बुक करा",
    "queue.currentToken": "सध्याचा टोकन",
    "queue.yourToken": "तुमचा टोकन",
    "queue.estimatedWait": "अंदाजित प्रतीक्षा वेळ",
    "queue.selectTime": "पसंतीची वेळ निवडा",
    "queue.book": "स्लॉट बुक करा",
    "map.title": "मंदिर नकाशा आणि नेव्हिगेशन",
    "map.legend": "सूची",
    "map.sanctum": "गर्भगृह",
    "map.mandapa": "सभामंडप",
    "map.pradakshina": "प्रदक्षिणा मार्ग",
    "map.entrance": "मुख्य प्रवेशद्वार",
    "map.exit": "बाहेर पडण्याचे द्वार",
    "map.facilities": "सुविधा",
    "map.parking": "पार्किंग",
    "map.lightShow": "लाईट अँड साऊंड शो",
    "emergency.title": "आपत्कालीन सेवा",
    "emergency.medicalHelp": "वैद्यकीय मदत",
    "emergency.security": "सुरक्षा इशारा",
    "emergency.lostFound": "हरवले व सापडले",
    "emergency.callNow": "आता कॉल करा",
    "services.title": "मंदिर सेवा आणि माहिती",
    "services.timings": "मंदिर वेळ",
    "services.aarti": "आरती वेळ",
    "services.attractions": "जवळची प्रेक्षणीय स्थळे",
    "services.accommodation": "निवास व्यवस्था",
    "services.transportation": "कसे पोहोचावे",
    "analytics.title": "गर्दी विश्लेषण डॅशबोर्ड",
    "analytics.hourlyFlow": "तासागणिक भाविक प्रवाह",
    "analytics.peakHours": "गर्दीचे मुख्य तास",
    "analytics.predictions": "गर्दीचा अंदाज",
    "common.minutes": "मिनिटे",
    "common.hours": "तास",
    "common.people": "भाविक",
    "common.capacity": "क्षमता",
  },

  sa: {
    "nav.home": "गृहम्",
    "nav.crowdMonitor": "जनसंमर्द दर्शनम्",
    "nav.darshanQueue": "दर्शन पङ्क्तिः",
    "nav.templeMap": "मन्दिर मानचित्रम्",
    "nav.emergency": "आपत्कालः",
    "nav.services": "सेवाः",
    "nav.analytics": "विश्लेषणम्",
    "nav.language": "भाषा",
    "hero.title": "सोमनाथ मन्दिरम्",
    "hero.subtitle": "दिव्य जनसंमर्द प्रबन्धन व्यवस्था",
    "hero.description":
      "पवित्रे सोमनाथ ज्योतिर्लिङ्गे प्रत्यक्ष जनसंमर्द निरीक्षणेन, आभासी पङ्क्त्या च सह सुगम दर्शनम् प्राप्नुवन्तु।",
    "hero.getStarted": "प्रारभ्यताम्",
    "hero.viewMap": "मन्दिर मानचित्रं पश्यतु",
    "crowd.title": "प्रत्यक्ष जनसंमर्द निरीक्षणम्",
    "crowd.currentFootfall": "वर्तमान भक्तसंख्या",
    "crowd.capacity": "मन्दिर क्षमता",
    "crowd.waitingTime": "प्रतीक्षा कालः",
    "crowd.crowdDensity": "संमर्द सान्द्रता",
    "crowd.low": "मन्दम्",
    "crowd.moderate": "मध्यमम्",
    "crowd.high": "अधिकम्",
    "crowd.critical": "अतिगम्भीरम्",
    "queue.title": "दर्शन पङ्क्ति प्रबन्धनम्",
    "queue.bookSlot": "दर्शन समयं निर्धारयतु",
    "queue.currentToken": "वर्तमान सङ्केतः",
    "queue.yourToken": "भवतः सङ्केतः",
    "queue.estimatedWait": "अनुमानित प्रतीक्षा कालः",
    "queue.selectTime": "इष्ट समयं वृणोतु",
    "queue.book": "समय आरक्षणम्",
    "map.title": "मन्दिर मानचित्रं मार्गदर्शनं च",
    "map.legend": "निर्देशिका",
    "map.sanctum": "गर्भगृहम्",
    "map.mandapa": "मण्डपम्",
    "map.pradakshina": "प्रदक्षिणा पथः",
    "map.entrance": "मुख्य प्रवेशद्वारम्",
    "map.exit": "निर्गम द्वारम्",
    "map.facilities": "सुविधाः",
    "map.parking": "वाहनस्थानम्",
    "map.lightShow": "ध्वनि-प्रकाश प्रदर्शनम्",
    "emergency.title": "आपत्कालीन सेवाः",
    "emergency.medicalHelp": "चिकित्सा सहायता",
    "emergency.security": "सुरक्षा सङ्केतः",
    "emergency.lostFound": "नष्टं प्राप्तं च",
    "emergency.callNow": "सम्पर्कं करोतु",
    "services.title": "मन्दिर सेवाः सूचनाः च",
    "services.timings": "मन्दिर समयः",
    "services.aarti": "आरती समयः",
    "services.attractions": "समीपस्थानि",
    "services.accommodation": "निवास व्यवस्था",
    "services.transportation": "मार्गदर्शनम्",
    "analytics.title": "संमर्द विश्लेषण फलकम्",
    "analytics.hourlyFlow": "होरा अनुसार भक्तप्रवाहः",
    "analytics.peakHours": "मुख्य काल विश्लेषणम्",
    "analytics.predictions": "आगामी संमर्द अनुमानम्",
    "common.minutes": "निमेषाः",
    "common.hours": "होराः",
    "common.people": "भक्ताः",
    "common.capacity": "क्षमता",
  },

  ta: {
    "nav.home": "முகப்பு",
    "nav.crowdMonitor": "கூட்டம் கண்காணிப்பு",
    "nav.darshanQueue": "தரிசன வரிசை",
    "nav.templeMap": "கோயில் வரைபடம்",
    "nav.emergency": "அவசரம்",
    "nav.services": "சேவைகள்",
    "nav.analytics": "பகுப்பாய்வு",
    "nav.language": "மொழி",
    "hero.title": "சோமநாதர் கோயில்",
    "hero.subtitle": "புனித கூட்ட மேலாண்மை அமைப்பு",
    "hero.description":
      "புனித சோமநாத ஜோதிர்லிங்கத்தில் நிகழ்நேர கூட்ட கண்காணிப்பு மற்றும் விர்ச்சுவல் வரிசையுடன் அமைதியான தரிசனம் பெறுங்கள்.",
    "hero.getStarted": "தொடங்குங்கள்",
    "hero.viewMap": "வரைபடத்தை காண்க",
    "crowd.title": "நிகழ்நேர கூட்ட கண்காணிப்பு",
    "crowd.currentFootfall": "தற்போதைய பக்தர்கள்",
    "crowd.capacity": "கோயில் கொள்ளளவு",
    "crowd.waitingTime": "சராசரி காத்திருப்பு நேரம்",
    "crowd.crowdDensity": "கூட்ட அடர்த்தி",
    "crowd.low": "குறைவு",
    "crowd.moderate": "நடுத்தரம்",
    "crowd.high": "அதிகம்",
    "crowd.critical": "மிக அதிகம்",
    "queue.title": "தரிசன வரிசை மேலாண்மை",
    "queue.bookSlot": "தரிசன நேரம் பதிவு செய்க",
    "queue.currentToken": "தற்போதைய டோக்கன்",
    "queue.yourToken": "உங்கள் டோக்கன்",
    "queue.estimatedWait": "மதிப்பிடப்பட்ட காத்திருப்பு",
    "queue.selectTime": "விரும்பிய நேரத்தை தேர்வு செய்க",
    "queue.book": "பதிவு செய்க",
    "map.title": "கோயில் வரைபடம் & வழிகாட்டுதல்",
    "map.legend": "விளக்கக் குறிப்பு",
    "map.sanctum": "கருவறை",
    "map.mandapa": "மண்டபம்",
    "map.pradakshina": "பிரதக்ஷிண பாதை",
    "map.entrance": "முதன்மை நுழைவாயில்",
    "map.exit": "வெளியேறும் வாயில்",
    "map.facilities": "வசதிகள்",
    "map.parking": "வாகன நிறுத்துமிடம்",
    "map.lightShow": "ஒளி & ஒலி நிகழ்ச்சி",
    "emergency.title": "அவசர சேவைகள்",
    "emergency.medicalHelp": "மருத்துவ உதவி",
    "emergency.security": "பாதுகாப்பு எச்சரிக்கை",
    "emergency.lostFound": "தொலைந்தவை & கிடைத்தவை",
    "emergency.callNow": "உடனே அழைக்கவும்",
    "services.title": "கோயில் சேவைகள் & தகவல்கள்",
    "services.timings": "கோயில் திறக்கும் நேரம்",
    "services.aarti": "ஆரத்தி நேரம்",
    "services.attractions": "அருகிலுள்ள இடங்கள்",
    "services.accommodation": "தங்குமிடம்",
    "services.transportation": "வந்தடையும் வழிகள்",
    "analytics.title": "கூட்ட பகுப்பாய்வு பலகை",
    "analytics.hourlyFlow": "மணிநேர பக்தர் வருகை",
    "analytics.peakHours": "அதிக கூட்ட நேரங்கள்",
    "analytics.predictions": "கூட்ட கணிப்பு",
    "common.minutes": "நிமிடங்கள்",
    "common.hours": "மணி நேரம்",
    "common.people": "மக்கள்",
    "common.capacity": "கொள்ளளவு",
  },

  te: {
    "nav.home": "హోమ్",
    "nav.crowdMonitor": "రద్దీ పర్యవేక్షణ",
    "nav.darshanQueue": "దర్శనం క్యూ",
    "nav.templeMap": "ఆలయ మ్యాప్",
    "nav.emergency": "అత్యవసరం",
    "nav.services": "సేవలు",
    "nav.analytics": "విశ్లేషణ",
    "nav.language": "భాష",
    "hero.title": "సోమనాథ దేవాలయం",
    "hero.subtitle": "దివ్య రద్దీ నిర్వహణ వ్యవస్థ",
    "hero.description":
      "పవిత్ర సోమనాథ జ్యోతిర్లింగంలో రియల్-టైమ్ రద్దీ పర్యవేక్షణ మరియు వర్చువల్ క్యూతో సులభతర దర్శనం పొందండి.",
    "hero.getStarted": "ప్రారంభించండి",
    "hero.viewMap": "ఆలయ మ్యాప్ చూడండి",
    "crowd.title": "రియల్-టైమ్ రద్దీ పర్యవేక్షణ",
    "crowd.currentFootfall": "ప్రస్తుత భక్తుల సంఖ్య",
    "crowd.capacity": "ఆలయ సామర్థ్యం",
    "crowd.waitingTime": "సగటు వేచి ఉండే సమయం",
    "crowd.crowdDensity": "రద్దీ సాంద్రత",
    "crowd.low": "తక్కువ",
    "crowd.moderate": "మధ్యస్థం",
    "crowd.high": "ఎక్కువ",
    "crowd.critical": "తీవ్రం",
    "queue.title": "దర్శనం క్యూ నిర్వహణ",
    "queue.bookSlot": "దర్శనం స్లాట్ బుక్ చేయండి",
    "queue.currentToken": "ప్రస్తుత టోకెన్",
    "queue.yourToken": "మీ టోకెన్",
    "queue.estimatedWait": "అంచనా వేసిన సమయం",
    "queue.selectTime": "సమయాన్ని ఎంచుకోండి",
    "queue.book": "స్లాట్ బుక్ చేయండి",
    "map.title": "ఆలయ మ్యాప్ మరియు నావిగేషన్",
    "map.legend": "సూచిక",
    "map.sanctum": "గర్భగుడి",
    "map.mandapa": "మండపం",
    "map.pradakshina": "ప్రదక్షిణ మార్గం",
    "map.entrance": "ప్రధాన ప్రవేశ ద్వారం",
    "map.exit": "నిష్క్రమణ ద్వారం",
    "map.facilities": "సౌకర్యాలు",
    "map.parking": "పార్కింగ్",
    "map.lightShow": "లైట్ & సౌండ్ షో",
    "emergency.title": "అత్యవసర సేవలు",
    "emergency.medicalHelp": "వైద్య సహాయం",
    "emergency.security": "భద్రతా హెచ్చరిక",
    "emergency.lostFound": "కోల్పోయినవి & దొరికినవి",
    "emergency.callNow": "ఇప్పుడే కాల్ చేయండి",
    "services.title": "ఆలయ సేవలు మరియు సమాచారం",
    "services.timings": "ఆలయ సమయాలు",
    "services.aarti": "హారతి సమయాలు",
    "services.attractions": "సమీప దర్శనీయ ప్రదేశాలు",
    "services.accommodation": "వసతి",
    "services.transportation": "ఎలా చేరుకోవాలి",
    "analytics.title": "రద్దీ విశ్లేషణ డాష్‌బోర్డ్",
    "analytics.hourlyFlow": "గంటవారీ భక్తుల ప్రవాహం",
    "analytics.peakHours": "పీక్ అవర్స్ విశ్లేషణ",
    "analytics.predictions": "రద్దీ అంచనాలు",
    "common.minutes": "నిమిషాలు",
    "common.hours": "గంటలు",
    "common.people": "భక్తులు",
    "common.capacity": "సామర్థ్యం",
  },

  bn: {
    "nav.home": "হোম",
    "nav.crowdMonitor": "ভিড় পর্যবেক্ষণ",
    "nav.darshanQueue": "দর্শন সারি",
    "nav.templeMap": "মন্দির মানচিত্র",
    "nav.emergency": "জরুরি সেবা",
    "nav.services": "সেবাসমূহ",
    "nav.analytics": "পরিসংখ্যান",
    "nav.language": "ভাষা",
    "hero.title": "সোমনাথ মন্দির",
    "hero.subtitle": "দিব্য ভিড় ব্যবস্থাপনা প্রণালী",
    "hero.description":
      "পবিত্র সোমনাথ জ্যোতির্লিঙ্গে রিয়েল-টাইম ভিড় পর্যবেক্ষণ এবং ভার্চুয়াল সারির মাধ্যমে শান্তিপূর্ণ দর্শন লাভ করুন।",
    "hero.getStarted": "শুরু করুন",
    "hero.viewMap": "মানচিত্র দেখুন",
    "crowd.title": "রিয়েল-টাইম ভিড় পর্যবেক্ষণ",
    "crowd.currentFootfall": "বর্তমান ভক্ত সমাগম",
    "crowd.capacity": "মন্দির ধারণক্ষমতা",
    "crowd.waitingTime": "গড় অপেক্ষার সময়",
    "crowd.crowdDensity": "ভিড়ের ঘনত্ব",
    "crowd.low": "কম",
    "crowd.moderate": "মাঝারি",
    "crowd.high": "বেশি",
    "crowd.critical": "খুব বেশি",
    "queue.title": "দর্শন সারি ব্যবস্থাপনা",
    "queue.bookSlot": "দর্শন সময় বুক করুন",
    "queue.currentToken": "বর্তমান টোকেন",
    "queue.yourToken": "আপনার টোকেন",
    "queue.estimatedWait": "আনুমানিক অপেক্ষার সময়",
    "queue.selectTime": "পছন্দের সময় নির্বাচন করুন",
    "queue.book": "বুক করুন",
    "map.title": "মন্দির মানচিত্র ও দিকনির্দেশ",
    "map.legend": "নির্দেশিকা",
    "map.sanctum": "গর্ভগৃহ",
    "map.mandapa": "মণ্ডপ",
    "map.pradakshina": "প্রদক্ষিণ পথ",
    "map.entrance": "প্রধান প্রবেশদ্বার",
    "map.exit": "প্রস্থান পথ",
    "map.facilities": "সুবিধাসমূহ",
    "map.parking": "পার্কিং",
    "map.lightShow": "আলো ও ধ্বনি অনুষ্ঠান",
    "emergency.title": "জরুরি সেবাসমূহ",
    "emergency.medicalHelp": "চিকিৎসা সহায়তা",
    "emergency.security": "নিরাপত্তা সতর্কতা",
    "emergency.lostFound": "হারানো ও প্রাপ্তি",
    "emergency.callNow": "এখনই কল করুন",
    "services.title": "মন্দির সেবা ও তথ্য",
    "services.timings": "মন্দির খোলার সময়",
    "services.aarti": "আরতি সময়সূচি",
    "services.attractions": "নিকটবর্তী দর্শনীয় স্থান",
    "services.accommodation": "থাকার ব্যবস্থা",
    "services.transportation": "যাতায়াত ব্যবস্থা",
    "analytics.title": "ভিড় বিশ্লেষণ ড্যাশবোর্ড",
    "analytics.hourlyFlow": "ঘণ্টাপ্রতি ভক্ত সমাগম",
    "analytics.peakHours": "শীর্ষ সময় বিশ্লেষণ",
    "analytics.predictions": "ভিড় পূর্বাভাস",
    "common.minutes": "মিনিট",
    "common.hours": "ঘণ্টা",
    "common.people": "ভক্তবৃন্দ",
    "common.capacity": "ধারণক্ষমতা",
  },
};
